<a href="https://colab.research.google.com/github/anshupandey/Generative-AI-for-Professionals/blob/main/EY2024%20/C14_RAG_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring Embeddeings from Azure OpenAI

In [ ]:
api_key = "xxxxxxxxx"
api_version = "2023-07-01-preview" # "2023-05-15"
azure_endpoint = "https://xxxxxxxx.openai.azure.com/"
embedding_model_name = "text-embedding-ada-002"

In [ ]:
import os
os.environ["OPENAI_API_VERSION"] = api_version
os.environ["AZURE_OPENAI_ENDPOINT"] = azure_endpoint
os.environ["AZURE_OPENAI_API_KEY"] = api_key
os.environ["AZURE_OPENAI_API_VERSION"] = api_version

In [ ]:
from langchain_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(azure_deployment=embedding_model_name)

In [ ]:
v1,v2,v3 = embeddings.embed_documents(["I like python programming, its a good programming language.",
                                    "Python is an amazing programming language, i like it a lot.",
                                    "Hello World, how are you?"])

In [ ]:
print(v1)

[-0.0013156682213057065, 0.0026297250217315626, -0.013612694997111383, -0.031015287990858433, -0.005349685887444464, -0.007979410676345383, 0.0002717140879173163, -0.04545299322555038, -0.0036352081114280235, -0.03145357584372632, 0.005017747621695131, 0.005958776437334645, 0.008379026290742008, 0.0006618624882294972, -0.0010626860862094016, 0.014734194569391004, 0.02266204350287146, -0.01945223094594995, 0.007676477055110787, 0.019258869753593616, -0.011982006915895594, 0.02315189309860428, 0.0035610860105839033, -0.019413558707478684, -0.012691001369384931, 0.018369402680819026, -0.0185369830017429, -0.02174679555866441, -0.0007843251782010057, -0.007296198025611083, 0.02549802131682881, -0.013818947556506525, -0.01669359760893514, 0.0025991094219982615, -0.02758633150750298, -0.00011037755724157664, -0.01350956778609124, -0.019310431496458544, 0.004966184481846345, 0.005987781081849382, 0.021153818751911448, 0.02406714104281133, -0.008140546245072428, -0.02233977236541737, -0.022030

In [ ]:
len(v1), len(v2), len(v3)

(1536, 1536, 1536)

In [ ]:
from numpy.linalg import norm
import numpy as np
# cosine similarity
np.dot(v1,v2)/(norm(v1),norm(v2))

array([0.95151839, 0.95151839])

In [ ]:
from numpy.linalg import norm
import numpy as np

np.dot(v1,v3)/(norm(v1),norm(v3))

array([0.76263389, 0.76263389])

In [ ]:
from numpy.linalg import norm
import numpy as np

np.dot(v2,v3)/(norm(v2),norm(v3))

array([0.76539893, 0.76539893])