<a href="https://colab.research.google.com/github/anshupandey/Generative-AI-for-Professionals/blob/main/EY2024/C14_RAG_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring Embeddeings from Azure OpenAI

In [3]:
!pip install langchain langchain-openai openai chromadb --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.0/375.0 kB 23.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 584.3/584.3 kB 32.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 60.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.8/273.8 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 5.7 MB/s eta 0:00

In [1]:
api_key = "xxxxxxxxxxxx"
api_version = "2024-02-01"
azure_endpoint = "https://xxxxxxx.openai.azure.com/"
embedding_model_name = "text-embedding-ada-002"

In [2]:
import os
os.environ["OPENAI_API_VERSION"] = api_version
os.environ["AZURE_OPENAI_ENDPOINT"] = azure_endpoint
os.environ["AZURE_OPENAI_API_KEY"] = api_key
os.environ["AZURE_OPENAI_API_VERSION"] = api_version

In [4]:
from langchain_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(azure_deployment=embedding_model_name)

In [5]:
v1,v2,v3 = embeddings.embed_documents(["I like python programming, its a good programming language.",
                                    "Python is an amazing programming language, i like it a lot.",
                                    "Hello World, how are you?"])

In [6]:
print(v1)

[-0.0013156682252883911, 0.002629725029692054, -0.013612695038318634, -0.031015288084745407, -0.005349685903638601, -0.007979410700500011, 0.0002717140887398273, -0.045452993363142014, -0.003635208122432232, -0.03145357593894005, 0.005017747636884451, 0.005958776455372572, 0.00837902631610632, 0.0006618624902330339, -0.001062686089426279, 0.014734194613993168, 0.022662043571472168, -0.019452231004834175, 0.007676477078348398, 0.01925886981189251, -0.011982006952166557, 0.02315189316868782, 0.003561086021363735, -0.019413558766245842, -0.012691001407802105, 0.0183694027364254, -0.01853698305785656, -0.021746795624494553, -0.0007843251805752516, -0.007296198047697544, 0.02549802139401436, -0.013818947598338127, -0.01669359765946865, 0.0025991094298660755, -0.027586331591010094, -0.00011037755757570267, -0.013509567826986313, -0.01931043155491352, 0.004966184496879578, 0.005987781099975109, 0.02115381881594658, 0.024067141115665436, -0.008140546269714832, -0.022339772433042526, -0.0220303

In [7]:
len(v1), len(v2), len(v3)

(1536, 1536, 1536)

In [8]:
from numpy.linalg import norm
import numpy as np
# cosine similarity
np.dot(v1,v2)/(norm(v1),norm(v2))

array([0.95151842, 0.95151839])

In [9]:
from numpy.linalg import norm
import numpy as np

np.dot(v1,v3)/(norm(v1),norm(v3))

array([0.76263393, 0.76263389])

In [10]:
from numpy.linalg import norm
import numpy as np

np.dot(v2,v3)/(norm(v2),norm(v3))

array([0.76539898, 0.76539896])

# Vector DB

In [17]:
import chromadb
chroma_client = chromadb.Client()

In [19]:
collection = chroma_client.create_collection(name="my_collection2")

In [20]:
collection.add(
    embeddings=[[1.2, 2.3, 4.5], [6.7, 8.2, 9.2]],
    documents=["Python is a programming language", "langchain is an framework"],
    metadatas=[{"source": "my_source"}, {"source": "my_source"}],
    ids=["id1", "id2"]
)

In [23]:
results = collection.query(
    query_embeddings=[[1.1, 1.1, 2.1]],
    n_results=2
)
results

{'ids': [['id1', 'id2']],
 'distances': [[7.210000038146973, 132.17999267578125]],
 'metadatas': [[{'source': 'my_source'}, {'source': 'my_source'}]],
 'embeddings': None,
 'documents': [['Python is a programming language',
   'langchain is an framework']],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}